#!/usr/bin/env python3
"""Q1-6 -- build a config that loads every level and asks what it dropped.

The question is not whether a map LOADS.  Q1-0 answered that from the file,
and Q1-2 showed the engine running.  This asks the next one: when the
software renderer runs out of surfaces or edges, it does not fail -- it
DROPS them and keeps going, counting what it threw away in r_outofsurfaces
and r_outofedges.  A map can therefore load perfectly and be drawn with
holes in it, and nothing says so unless asked.

r_reportsurfout and r_reportedgeout are that question.  Both counters are
incremented in r_draw.c (C code, so they work with id386 = 0 -- checked) and
reset every frame in R_SetupFrame, so what gets printed describes one frame.

WHICH MAPS.  Only the ten with an info_player_start.  The other thirteen
.bsp files in the paks are brush models -- ammo boxes, health packs, rocks --
which entities reference and the engine loads as part of a level.  Asking
`map b_rock1` would load a world with no player start, which tests nothing
and would only add noise.  They are exercised anyway, by the levels that
use them.

WHAT THIS DOES NOT ANSWER.  Each map is looked at from the player start and
nowhere else.  A shortfall that only happens in the far corner of a level
will not appear here.  This is a floor, not a certificate.

    python3 make-mapwalk-cfg.py <pak> [pak...] > q16.cfg
"""
import struct
import sys

FRAMES_PER_MAP = 60


def levels(paths):
    out = []
    for path in paths:
        with open(path, "rb") as f:
            magic, dirofs, dirlen = struct.unpack("<4sii", f.read(12))
            if magic != b"PACK":
                raise SystemExit("%s is not a pak" % path)
            f.seek(dirofs)
            raw = f.read(dirlen)
            for i in range(dirlen // 64):
                rec = raw[i * 64:(i + 1) * 64]
                name = rec[:56].split(b"\0")[0].decode("latin1")
                pos, ln = struct.unpack("<ii", rec[56:])
                if not name.lower().endswith(".bsp"):
                    continue
                f.seek(pos)
                hdr = f.read(4 + 15 * 8)
                eofs, elen = struct.unpack_from("<ii", hdr, 4)   # LUMP_ENTITIES
                f.seek(pos + eofs)
                ents = f.read(elen).decode("latin1", "replace")
                if "info_player_start" in ents:
                    out.append(name.split("/")[-1][:-4])
    return sorted(set(out))


def main(argv):
    if len(argv) < 2:
        print(__doc__)
        return 2
    maps = levels(argv[1:])
    if not maps:
        print("no levels found", file=sys.stderr)
        return 1
    print("// generated by make-mapwalk-cfg.py -- Q1-6")
    print("// %d levels, %d frames each" % (len(maps), FRAMES_PER_MAP))
    print("r_reportsurfout 1")
    print("r_reportedgeout 1")
    for m in maps:
        print("")
        print("echo ---- %s ----" % m)
        print("map %s" % m)
        # One frame per wait.  Enough of them that the level has finished
        # connecting and has been drawn a good many times before moving on.
        for _ in range(FRAMES_PER_MAP):
            print("wait")
    print("")
    print("echo ---- done ----")
    print("quit")
    return 0


if __name__ == "__main__":
    sys.exit(main(sys.argv))
